---
title: "Video Game Popularity Over Time"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r include = FALSE}
library(lubridate)
library(dplyr)
library(ggplot2)
library(readr)
library(tidytuesdayR)
library(shiny)
library(plotly)
library(ggthemes)
library(forcats)
library(scales)
theme_set(theme_tufte()) 

tuesdata <- tidytuesdayR::tt_load('2021-03-16') 



games <- tuesdata$games %>%
  mutate(avg_peak_perc = parse_number(avg_peak_perc) / 100) %>%
  mutate(date = ymd(paste(year, month, 1))) %>%
  filter(date > min(date)) %>%
  mutate(month = fct_reorder(month, month(date))) %>%
  mutate(gamename = fct_reorder(gamename, -avg))

game_names <- levels(games$gamename)
```

```{r eruptions, echo=FALSE}
inputPanel(
  selectizeInput("games", label = "Games:",
              choices = game_names,
              selected = head(game_names, 9),
              multiple = TRUE)
  
 
)

renderPlotly({
  req(input$games)
  
 g <- games %>%
    filter(gamename %in% input$games) %>%
    ggplot(aes(date, avg)) +
    geom_line() +
    expand_limits(y = 0) +
    scale_y_continuous(labels = comma) +
    facet_wrap(~ gamename, scales = "free_y") +
    labs(x = "Date",
         y = "Ave number of players")
 
 ggplotly(g)
  })

```

